# Generated by Django 2.2.7 on 2020-01-16 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resources.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=255, verbose_name='Subject')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalResource',
            fields=[
                ('resource_id', models.CharField(default=resources.models.generate_id, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Resource description')),
                ('resource_uri', models.URLField(verbose_name='Resource address')),
                ('rsrc_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsrc_owner', to=settings.AUTH_USER_MODEL)),
                ('rsrc_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsrc_subject', to='resources.Subject', verbose_name='Subject')),
            ],
        ),
    ]
