# Generated by Django 2.2.7 on 2020-01-15 19:12

from django.db import migrations, models
import django.db.models.deletion
import resources.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalResource',
            fields=[
                ('resource_id', models.CharField(default=resources.models.generate_id, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis')),
                ('resource_uri', models.URLField(verbose_name='Adres zasobu')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Subject')),
            ],
        ),
    ]
