# Generated by Django 2.2.7 on 2020-01-15 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='name',
        ),
        migrations.AddField(
            model_name='subject',
            name='sub_name',
            field=models.CharField(default=None, max_length=255, verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='externalresource',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='externalresource',
            name='resource_uri',
            field=models.URLField(verbose_name='Resource address'),
        ),
        migrations.AlterField(
            model_name='externalresource',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='resources.Subject'),
        ),
        migrations.AlterField(
            model_name='externalresource',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
