# Generated by Django 2.2.7 on 2019-11-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('pathToFile', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('login', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
