# Generated by Django 2.2.7 on 2019-11-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesWithPath', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='FileWithPath',
        ),
    ]
