# Generated by Django 2.2.7 on 2020-01-16 10:34

import Files.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('file_id', models.CharField(default=Files.models.generate_id, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('file', models.FileField(max_length=250, upload_to='uploads/', verbose_name='File')),
                ('file_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_owner', to=settings.AUTH_USER_MODEL)),
                ('file_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_subject', to='resources.Subject', verbose_name='Subject')),
            ],
        ),
    ]
