# Generated by Django 2.2.7 on 2020-01-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(max_length=250, upload_to='uploads/', verbose_name='Plik'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Tytuł'),
        ),
    ]
