# Generated by Django 2.2.7 on 2020-01-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0002_auto_20200115_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(max_length=250, upload_to='uploads/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
    ]
